package org.matrix.TEESimulator.attestation

import android.security.keystore.KeyProperties
import java.nio.charset.StandardCharsets
import java.security.PrivateKey
import java.security.PublicKey
import java.security.cert.Certificate
import java.security.cert.X509Certificate
import java.security.interfaces.ECPrivateKey
import java.security.interfaces.ECPublicKey
import java.security.interfaces.RSAPrivateKey
import java.security.interfaces.RSAPublicKey
import java.util.Date
import org.bouncycastle.asn1.*
import org.bouncycastle.asn1.x509.Extension
import org.bouncycastle.cert.X509CertificateHolder
import org.bouncycastle.cert.X509v3CertificateBuilder
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter
import org.bouncycastle.jce.provider.BouncyCastleProvider
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder
import org.matrix.TEESimulator.config.ConfigurationManager
import org.matrix.TEESimulator.logging.SystemLogger
import org.matrix.TEESimulator.pki.KeyBox
import org.matrix.TEESimulator.pki.KeyBoxManager
import org.matrix.TEESimulator.util.toHex

/**
 * Handles the modification (patching) of Android Key Attestation extensions within certificates.
 *
 * This object's primary function is to take a certificate chain generated by the real TEE, replace
 * its attestation data with simulated values, and then re-sign the leaf certificate with a custom
 * key, building a new, valid certificate chain.
 */
object AttestationPatcher {

    /**
     * Patches a full certificate chain by modifying the leaf's attestation and rebuilding the chain
     * with the correct custom signing certificates. This is the single entry point for patching.
     *
     * @param originalChain The original certificate chain from the hardware. The leaf must be at
     *   index 0.
     * @param uid The UID of the application requesting the certificate.
     * @return A new, cryptographically valid, patched certificate chain. Returns the original chain
     *   on any failure.
     */
    fun patchCertificateChain(
        originalChain: Array<Certificate>?,
        uid: Int,
        notBefore: Date? = null,
        notAfter: Date? = null,
    ): Array<Certificate> {
        if (originalChain.isNullOrEmpty()) {
            SystemLogger.error("Attempted to patch a null or empty certificate chain for UID $uid.")
            return originalChain ?: emptyArray()
        }

        return runCatching {
                val originalLeaf = originalChain[0] as X509Certificate
                val originalLeafHolder = X509CertificateHolder(originalLeaf.encoded)

                // 1. Attempt to parse the existing attestation extension. If it doesn't exist,
                // there's nothing to patch.
                val parsedAttestation =
                    parseAttestationExtension(originalLeafHolder) ?: return originalChain

                // 2. Get the appropriate keybox for the given algorithm to sign the new
                // certificate.
                val keybox = getKeyboxForUidAndAlgorithm(uid, originalLeaf.sigAlgName)

                // 3. Create the new, patched leaf certificate.
                val patchedLeaf =
                    createPatchedLeafCertificate(
                        originalLeafHolder,
                        parsedAttestation,
                        keybox,
                        uid,
                        notBefore,
                        notAfter,
                    )

                // 4. Construct the NEW, VALID chain by prepending the patched leaf to the keybox's
                // chain.
                val newChain = listOf(patchedLeaf) + keybox.certificates

                SystemLogger.info(
                    "Successfully rebuilt a valid, patched certificate chain for UID $uid."
                )
                newChain.toTypedArray()
            }
            .getOrElse {
                SystemLogger.error(
                    "Failed to patch and rebuild certificate chain for UID $uid.",
                    it,
                )
                originalChain // Return the original chain on any error.
            }
    }

    /**
     * Creates a new leaf certificate with a modified attestation extension.
     *
     * @param originalLeafHolder A Bouncy Castle holder for the original leaf certificate.
     * @param parsedAttestation The parsed components of the original attestation.
     * @param keybox The KeyBox containing the new issuer certificate and signing key.
     * @param uid The UID of the application requesting the certificate.
     * @return A new [Certificate] object.
     */
    private fun createPatchedLeafCertificate(
        originalLeafHolder: X509CertificateHolder,
        parsedAttestation: ParsedAttestation,
        keybox: KeyBox,
        uid: Int,
        notBefore: Date? = null,
        notAfter: Date? = null,
    ): Certificate {
        // The issuer of our new leaf is the subject of the first certificate in our custom keybox
        // chain.
        val newIssuer = X509CertificateHolder(keybox.certificates[0].encoded).subject

        val effectiveNotBefore = notBefore ?: originalLeafHolder.notBefore
        val effectiveNotAfter = notAfter ?: originalLeafHolder.notAfter
        if (notBefore != null || notAfter != null) {
            SystemLogger.debug(
                "Overriding cert dates: notBefore=${effectiveNotBefore} (was ${originalLeafHolder.notBefore}), notAfter=${effectiveNotAfter} (was ${originalLeafHolder.notAfter})"
            )
        }

        val builder =
            X509v3CertificateBuilder(
                newIssuer,
                originalLeafHolder.serialNumber,
                effectiveNotBefore,
                effectiveNotAfter,
                originalLeafHolder.subject,
                originalLeafHolder.subjectPublicKeyInfo,
            )

        // Create the new, patched attestation extension.
        val patchedExtension = createPatchedAttestationExtension(parsedAttestation, uid)

        // Copy all other extensions from the original certificate, except for the attestation.
        originalLeafHolder.extensions.extensionOIDs.forEach {
            builder.addExtension(
                if (it == ATTESTATION_OID) patchedExtension else originalLeafHolder.getExtension(it)
            )
        }

        // Sign the new leaf with the keybox key. The signature algorithm must match THAT key, not
        // the original leaf's: when an RSA leaf is re-rooted under an EC-only keybox, this signs
        // with ECDSA. The RSA subject public key is untouched and the chain still verifies to the
        // keybox root.
        val signer =
            JcaContentSignerBuilder(signatureAlgorithmFor(keybox.keyPair.private))
                .setProvider(BouncyCastleProvider.PROVIDER_NAME)
                .build(keybox.keyPair.private)
        val newCertificate = JcaX509CertificateConverter().getCertificate(builder.build(signer))

        // Log the signature of the newly created certificate to observe its non-deterministic
        // nature.
        val signatureBytes = (newCertificate as X509Certificate).signature
        SystemLogger.verbose { "Signature of patched leaf cert: ${signatureBytes.toHex()}" }

        return newCertificate
    }

    /**
     * Retrieves the appropriate signing KeyBox (KeyPair and certificate chain) for a given UID
     * based on a specified algorithm identifier.
     *
     * @param uid The UID of the application for which the signing is being performed.
     * @param algorithm A string representing the desired algorithm. This can be either:
     *     1. A simple key type like "RSA" or "EC".
     *     2. A full JCA signature algorithm name like "SHA256withRSA".
     *
     * @return The algorithm-matching [KeyBox] when present, otherwise any available key (fail-safe).
     * @throws IllegalArgumentException only if the keybox file contains no usable signing key.
     */
    private fun getKeyboxForUidAndAlgorithm(uid: Int, algorithm: String): KeyBox {
        val keyboxFile = ConfigurationManager.getKeyboxFileForUid(uid)

        // Normalize the algorithm name. The input might be a full signature algorithm
        // (e.g., "SHA256withRSA") or just the key type (e.g., "RSA").
        val keyType =
            when {
                algorithm.contains("RSA", ignoreCase = true) -> KeyProperties.KEY_ALGORITHM_RSA
                algorithm.contains("EC", ignoreCase = true) ->
                    KeyProperties.KEY_ALGORITHM_EC // This also covers "ECDSA"
                else -> algorithm // If no match, assume it's already a simple key type string.
            }

        val matching = KeyBoxManager.getAttestationKey(keyboxFile, keyType)
        if (matching != null) return matching

        // Fail-safe: no algorithm-matching key (e.g. an EC-only Google keybox asked to re-root an
        // RSA leaf). Fall back to any available key instead of throwing -- a throw here aborts the
        // patch and the caller hands back the device's REAL, unlocked attestation. Re-signing under
        // the available key keeps the chain rooted at the keybox with our forged, locked Root of
        // Trust; a leaf's signature algorithm is independent of its subject key, so an RSA subject
        // key signs validly under an EC keybox key.
        return KeyBoxManager.getAnyAttestationKey(keyboxFile)?.also {
            SystemLogger.debug(
                "No '$keyType' attestation key in $keyboxFile for UID $uid; re-signing under the " +
                    "available keybox key to avoid leaking the device's real attestation."
            )
        }
            ?: throw IllegalArgumentException(
                "No usable attestation key for UID $uid in file $keyboxFile (requested '$keyType')"
            )
    }

    /** SHA-256 signature algorithm name matching the keybox signing key's type. */
    private fun signatureAlgorithmFor(signingKey: PrivateKey): String =
        when (signingKey) {
            is ECPrivateKey -> "SHA256withECDSA"
            is RSAPrivateKey -> "SHA256withRSA"
            else ->
                throw IllegalArgumentException(
                    "Unsupported keybox signing key type: ${signingKey.algorithm}"
                )
        }

    /** Recursively formats an ASN1Primitive into a concise, readable string. */
    fun formatAsn1Primitive(obj: ASN1Encodable?): String {
        val primitive = obj?.toASN1Primitive()
        return when (primitive) {
            null -> "NULL"
            is ASN1Integer -> primitive.value.toString()
            is ASN1Enumerated -> primitive.value.toString()
            is ASN1Boolean -> primitive.isTrue.toString()
            is ASN1Null -> "NULL"
            is ASN1OctetString -> {
                val bytes = primitive.octets
                // Attempt to decode as a printable string, otherwise show hex
                if (bytes.all { it >= 32 && it < 127 }) {
                    "\"${String(bytes, StandardCharsets.UTF_8)}\""
                } else if (bytes.isEmpty()) {
                    "\"\""
                } else {
                    "#" + bytes.toHex()
                }
            }
            is ASN1TaggedObject ->
                "[TAG ${primitive.tagNo}]${formatAsn1Primitive(primitive.baseObject)}"
            is ASN1Sequence ->
                primitive
                    .map { formatAsn1Primitive(it) }
                    .joinToString(prefix = "[", postfix = "]", separator = ", ")
            is ASN1Set ->
                primitive
                    .map { formatAsn1Primitive(it) }
                    .joinToString(prefix = "{", postfix = "}", separator = ", ")
            else -> primitive.toString() // Fallback for other types
        }
    }

    /** Reverse map of attestation tag number to its symbolic name, e.g. 704 -> "ROOT_OF_TRUST". */
    private val attestTagNames: Map<Int, String> by lazy {
        AttestationConstants::class
            .java
            .fields
            .filter { it.name.startsWith("TAG_") && it.type == Int::class.java }
            .associate { (it.get(null) as Int) to it.name.removePrefix("TAG_") }
    }

    /**
     * Renders the full key-attestation extension of [cert] as a single structured line for the
     * diagnostic dossier, or null when the certificate carries no attestation extension. This is the
     * ground-truth view of what we actually emitted, so any divergence from a genuine TEE surfaces
     * directly as a differing field rather than having to be guessed.
     */
    fun formatAttestationExtension(cert: X509Certificate): String? {
        val rawExtension = cert.getExtensionValue(ATTESTATION_OID.id) ?: return null
        return runCatching {
                val keyDescriptionDer = ASN1OctetString.getInstance(rawExtension).octets
                formatKeyDescription(ASN1Sequence.getInstance(keyDescriptionDer))
            }
            .getOrElse { "<unparseable attestation extension: ${it.message}>" }
    }

    /** Renders the identity fields of every certificate in a returned chain for the dossier. */
    fun formatCertChain(chain: List<Certificate>): String =
        chain
            .mapIndexed { index, cert ->
                val x509 = cert as? X509Certificate ?: return@mapIndexed "[$index] <non-X509>"
                "[$index] subject=${x509.subjectX500Principal.name} " +
                    "issuer=${x509.issuerX500Principal.name} " +
                    "serial=${x509.serialNumber.toString(16)} " +
                    "notBefore=${x509.notBefore} notAfter=${x509.notAfter}"
            }
            .joinToString(separator = " ; ")

    /**
     * Verifies every certificate in [chain] against its issuer and renders the outcome for the
     * dossier. The forged chain is [leaf] + keybox certs, so edge 0<-1 proves the leaf was signed by
     * the key matching the issuer cert and later edges test the keybox's own chain. For an RSA issuer
     * it also reports signature-bytes vs modulus-bytes: a signature longer than the modulus is the
     * exact DATA_TOO_LARGE_FOR_KEY_SIZE the app's verifier throws, so the offending edge is
     * identifiable from the log alone.
     */
    fun formatChainVerification(chain: List<Certificate>): String {
        if (chain.size < 2) return "<single cert; nothing to chain-verify>"
        return (0 until chain.size - 1).joinToString(separator = " ; ") { i ->
            val child = chain[i] as? X509Certificate ?: return@joinToString "[$i]<non-X509>"
            val parent =
                chain[i + 1] as? X509Certificate ?: return@joinToString "[$i]<parent non-X509>"
            val outcome =
                runCatching {
                        child.verify(parent.publicKey)
                        "OK"
                    }
                    .getOrElse { "FAIL(${it.javaClass.simpleName}: ${it.message?.take(80)})" }
            val rsaSizes =
                (parent.publicKey as? RSAPublicKey)?.let {
                    val sigBytes = child.signature.size
                    val modBytes = (it.modulus.bitLength() + 7) / 8
                    " sig=${sigBytes}B mod=${modBytes}B" + if (sigBytes > modBytes) " OVERSIZE" else ""
                } ?: ""
            "[$i]${describeKey(child.publicKey)}<-[${i + 1}]${describeKey(parent.publicKey)}:" +
                "$outcome$rsaSizes"
        }
    }

    /**
     * Per-cert key type/size, subject, issuer, and signature length, for reconstructing the chain a
     * caller verifies. The signature length reveals the signer's key size, so a 4096-bit signature
     * landing on a 2048-bit issuer (DATA_TOO_LARGE) is visible without the certificate bytes.
     */
    fun formatChainKeys(chain: List<Certificate>): String =
        chain
            .mapIndexed { index, cert ->
                val x509 = cert as? X509Certificate ?: return@mapIndexed "[$index]<non-X509>"
                "[$index]${describeKey(x509.publicKey)} " +
                    "subj=${x509.subjectX500Principal.name} " +
                    "iss=${x509.issuerX500Principal.name} " +
                    "sigLen=${x509.signature.size}B"
            }
            .joinToString(separator = " ; ")

    private fun describeKey(key: PublicKey): String =
        when (key) {
            is RSAPublicKey -> "RSA${key.modulus.bitLength()}"
            is ECPublicKey -> "EC${key.params.curve.field.fieldSize}"
            else -> key.algorithm
        }

    private fun formatKeyDescription(seq: ASN1Sequence): String {
        val fields = seq.toArray()
        return "attestVer=${formatAsn1Primitive(fields[AttestationConstants.KEY_DESCRIPTION_ATTESTATION_VERSION_INDEX])} " +
            "attestSecLvl=${formatSecurityLevel(fields[AttestationConstants.KEY_DESCRIPTION_ATTESTATION_SECURITY_LEVEL_INDEX])} " +
            "kmVer=${formatAsn1Primitive(fields[AttestationConstants.KEY_DESCRIPTION_KEYMINT_VERSION_INDEX])} " +
            "kmSecLvl=${formatSecurityLevel(fields[AttestationConstants.KEY_DESCRIPTION_KEYMINT_SECURITY_LEVEL_INDEX])} " +
            "challenge=${formatAsn1Primitive(fields[AttestationConstants.KEY_DESCRIPTION_ATTESTATION_CHALLENGE_INDEX])} " +
            "uniqueId=${formatAsn1Primitive(fields[AttestationConstants.KEY_DESCRIPTION_UNIQUE_ID_INDEX])} " +
            "sw=${formatAuthorizationList(fields[AttestationConstants.KEY_DESCRIPTION_SOFTWARE_ENFORCED_INDEX])} " +
            "tee=${formatAuthorizationList(fields[AttestationConstants.KEY_DESCRIPTION_TEE_ENFORCED_INDEX])}"
    }

    private fun formatSecurityLevel(obj: ASN1Encodable): String {
        val level = (obj.toASN1Primitive() as? ASN1Enumerated)?.value?.toInt()
        val name =
            when (level) {
                0 -> "Software"
                1 -> "TEE"
                2 -> "StrongBox"
                else -> "?"
            }
        return "$level($name)"
    }

    private fun formatAuthorizationList(obj: ASN1Encodable): String {
        val seq = obj.toASN1Primitive() as? ASN1Sequence ?: return formatAsn1Primitive(obj)
        return seq
            .map { element ->
                val tagged = element as? ASN1TaggedObject ?: return@map formatAsn1Primitive(element)
                val name = attestTagNames[tagged.tagNo] ?: "TAG"
                val value =
                    if (tagged.tagNo == AttestationConstants.TAG_ROOT_OF_TRUST)
                        formatRootOfTrust(tagged.baseObject)
                    else formatAsn1Primitive(tagged.baseObject)
                "${tagged.tagNo}($name)=$value"
            }
            .joinToString(prefix = "[", postfix = "]", separator = ", ")
    }

    /**
     * Decodes the Root of Trust sub-sequence explicitly — it is the field a detector most often uses
     * to unmask a simulated TEE (a random verifiedBootKey, an unexpected verifiedBootState, or a
     * deviceLocked that disagrees with the bootloader all live here).
     */
    private fun formatRootOfTrust(obj: ASN1Encodable): String {
        val fields = (obj.toASN1Primitive() as? ASN1Sequence)?.toArray() ?: return formatAsn1Primitive(obj)
        val state = fields.getOrNull(AttestationConstants.ROOT_OF_TRUST_VERIFIED_BOOT_STATE_INDEX)
        val stateName =
            when ((state?.toASN1Primitive() as? ASN1Enumerated)?.value?.toInt()) {
                0 -> "Verified"
                1 -> "SelfSigned"
                2 -> "Unverified"
                3 -> "Failed"
                else -> "?"
            }
        return "[bootKey=${formatAsn1Primitive(fields.getOrNull(AttestationConstants.ROOT_OF_TRUST_VERIFIED_BOOT_KEY_INDEX))}, " +
            "deviceLocked=${formatAsn1Primitive(fields.getOrNull(AttestationConstants.ROOT_OF_TRUST_DEVICE_LOCKED_INDEX))}, " +
            "verifiedBootState=${formatAsn1Primitive(state)}($stateName), " +
            "bootHash=${formatAsn1Primitive(fields.getOrNull(AttestationConstants.ROOT_OF_TRUST_VERIFIED_BOOT_HASH_INDEX))}]"
    }

    // Function to check if a given ASN1Sequence contains the Root of Trust tag.
    private fun sequenceContainsRootOfTrust(seq: ASN1Encodable): Boolean {
        if (seq !is ASN1Sequence) return false
        return seq.any { element ->
            (element as? ASN1TaggedObject)?.tagNo == AttestationConstants.TAG_ROOT_OF_TRUST
        }
    }

    /** Parses the critical components from an existing attestation extension. */
    private fun parseAttestationExtension(certHolder: X509CertificateHolder): ParsedAttestation? {
        val extension = certHolder.getExtension(ATTESTATION_OID) ?: return null
        val sequence = ASN1Sequence.getInstance(extension.extnValue.octets)
        val allFields = sequence.toArray()

        // Check if the fields are in the wrong order and swap them if necessary.
        val softwareEnforcedCandidate =
            allFields[AttestationConstants.KEY_DESCRIPTION_SOFTWARE_ENFORCED_INDEX]
        val teeEnforcedCandidate =
            allFields[AttestationConstants.KEY_DESCRIPTION_TEE_ENFORCED_INDEX]
        // The signature of a swapped order: the RoT is in the software list's position.
        if (
            sequenceContainsRootOfTrust(softwareEnforcedCandidate) &&
                !sequenceContainsRootOfTrust(teeEnforcedCandidate)
        ) {
            // Swap the elements in the array to restore the standard order.
            allFields[AttestationConstants.KEY_DESCRIPTION_SOFTWARE_ENFORCED_INDEX] =
                teeEnforcedCandidate
            allFields[AttestationConstants.KEY_DESCRIPTION_TEE_ENFORCED_INDEX] =
                softwareEnforcedCandidate
        }

        val teeEnforced =
            allFields[AttestationConstants.KEY_DESCRIPTION_TEE_ENFORCED_INDEX] as ASN1Sequence

        var originalRootOfTrust: ASN1Encodable? = null
        val teeEnforcedMap = mutableMapOf<Int, ASN1TaggedObject>()

        teeEnforced.forEach { element ->
            val taggedObject = element as ASN1TaggedObject
            if (taggedObject.tagNo == AttestationConstants.TAG_ROOT_OF_TRUST) {
                originalRootOfTrust = taggedObject.baseObject.toASN1Primitive()
            } else {
                teeEnforcedMap[taggedObject.tagNo] = taggedObject
            }
        }
        return ParsedAttestation(allFields, teeEnforcedMap, originalRootOfTrust)
    }

    /** Constructs a new, patched attestation extension using simulated device properties. */
    private fun createPatchedAttestationExtension(parsed: ParsedAttestation, uid: Int): Extension {
        val (allFields, teeEnforcedMap, originalRootOfTrust) = parsed

        SystemLogger.verbose {
            val formattedString =
                allFields.joinToString(separator = ", ") { formatAsn1Primitive(it) }
            "Original attestation data: $formattedString"
        }

        // Build the new Root of Trust and add/replace it in the map.
        val newRootOfTrust = AttestationBuilder.buildRootOfTrust(originalRootOfTrust)
        teeEnforcedMap[AttestationConstants.TAG_ROOT_OF_TRUST] =
            DERTaggedObject(true, AttestationConstants.TAG_ROOT_OF_TRUST, newRootOfTrust)

        // Get the desired state for simulated properties.
        val simulatedProperties = AttestationBuilder.getSimulatedHardwareProperties(uid)

        // Apply the desired state: update, add, or remove properties from the original map.
        simulatedProperties.forEach { (tag, value) ->
            if (value != null) {
                // If the value is not null, add or update it.
                teeEnforcedMap[tag] = value
            } else {
                // If the value is null, remove the tag from the map.
                teeEnforcedMap.remove(tag)
            }
        }

        // Re-assemble the TEE enforced list from the map's values, sorting for DER compliance.
        val sortedElements = teeEnforcedMap.values.sortedBy { it.tagNo }
        val sortedTeeEnforced = DERSequence(sortedElements.toTypedArray())

        allFields[AttestationConstants.KEY_DESCRIPTION_TEE_ENFORCED_INDEX] = sortedTeeEnforced
        val patchedSequence = DERSequence(allFields)
        SystemLogger.verbose {
            val formattedString =
                patchedSequence.joinToString(separator = ", ") { formatAsn1Primitive(it) }
            "Patched  attestation data: $formattedString"
        }
        val patchedOctets = DEROctetString(patchedSequence)

        return Extension(ATTESTATION_OID, false, patchedOctets)
    }

    /** Helper data class to hold the parsed components of an attestation extension. */
    private data class ParsedAttestation(
        val allFields: Array<ASN1Encodable>,
        val teeEnforcedMap: MutableMap<Int, ASN1TaggedObject>,
        val rootOfTrust: ASN1Encodable?,
    )
}
