#!/system/bin/sh

MODDIR=$1
shift

if [ -z "$MODDIR" ] || [ ! -d "$MODDIR" ]; then
    exit 79
fi

case "${LD_PRELOAD:-}" in
    '') ;;
    *) exit 79 ;;
esac

tracer_pid=$(awk '/^TracerPid:/ {print $2; exit}' /proc/self/status 2>/dev/null)
case "$tracer_pid" in
    ''|0) ;;
    *) exit 79 ;;
esac

if [ ! -x "$MODDIR/supervisor" ] || ! "$MODDIR/supervisor" --runtime-check "$MODDIR"; then
    exit 79
fi

if [ -f "$MODDIR/classes.dex" ]; then
    CLASSPATH="$MODDIR/classes.dex"
elif [ -f "$MODDIR/service.apk" ]; then
    CLASSPATH="$MODDIR/service.apk"
else
    exit 79
fi

exec /system/bin/app_process -Djava.class.path="$CLASSPATH" "$MODDIR" --nice-name=TEESimulator org.matrix.TEESimulator.App "$@"
